--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AzaleeX/FactionLegends
build-by-default: true
branches:
- stable
projects:
  FactionLegends:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
...
