---

#   _____          _   _             _                              _
#  |  ___|_ _  ___| |_(_) ___  _ __ | |    ___  __ _  ___ _ __   __| |___
#  | |_ / _` |/ __| __| |/ _ \| '_ \| |   / _ \/ _` |/ _ \ '_ \ / _` / __|
#  |  _| (_| | (__| |_| | (_) | | | | |__|  __/ (_| |  __/ | | | (_| \__ \
#  |_|  \__,_|\___|\__|_|\___/|_| |_|_____\___|\__, |\___|_| |_|\__,_|___/
#                                              |___/
# @author AzaleeX
# @link https://github.com/AzaleeX

# Database type (mysql|sqlite)
# if the database type is mysql you must fill in the information if it's sqlite all parameters will be ignored
DATABASE-TYPE:
    type: sqlite
    sqlite:
      file: "factionlegends.sqlite"
    mysql:
      host: localhost
      username: root
      password: ""
      schema: "factionlegends" #Change this
    worker-limit: 1
#The plugin has multiple language support:
#- American English (en-US)
#- British English (en-GB)
#- French (FR)
language: "en-US"

